### ISSUE TITLE
Brew install not working

### ISSUE THREAD

**Issue by parljohn** [phpv8/homebrew-tap#2] opened 2018-12-08 23:26 UTC
Getting the following when trying to install v8@6.6 :

==> Cloning https://chromium.googlesource.com/chromium/tools/depot_tools.git
Updating /Users/pjohnson/Library/Caches/Homebrew/v8@6.6--depot_tools--git
==> Checking out revision 92745a5b0e2e7593fabe8b831cb913cd548b257b
HEAD is now at 92745a5b bot_update: Fix syncing to origin/*.
HEAD is now at 92745a5b bot_update: Fix syncing to origin/*.
==> gclient root
Error: An exception occurred within a child process:
  NoMethodError: undefined method `undent' for #<String:0x00007fc2e59d4978>

**Comment by pinepain** [comment] 2019-01-31 07:03
Hi there, it's bee a while since I wrote this tap and unfortunately, I don't use it much anymore. I just tried to install one of the formula from it and it worked for me ok. If the issue is still relevant for you, could you please list your macos version (`sw_vers` output would be fine), xcode version (`xcodebuild -version`), ruby version ( `ruby -v`) and homebrew version (`brew --version`).

I can say that it works OK for me having following configuration:
```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.14.2
BuildVersion:	18C54

$ xcodebuild -version
Xcode 10.1
Build version 10B61

$ brew --version
Homebrew 1.9.3-77-g2062c51
Homebrew/homebrew-core (git revision 5096c; last commit 2019-01-31)
Homebrew/homebrew-cask (git revision 5206b; last commit 2019-01-31)

$ ruby -v
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
```
However, my system may have other deps installed that are indirectly affect the result I have so it's just for the reference.

**Comment by pinepain** [comment] 2019-01-31 11:30
As it came up, none of v8 under 6.9.sth would work on modern macos, so closing this as there is little to be done but bump to more recent v8 version.

**Closed as completed by pinepain** 2019-01-31 11:30 UTC
Labels: bug
